
services:
  app:
    image: openjdk:21-jdk-slim
    ports:
      - "8080:8080"
    environment:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
        DB_URL: ${DB_URL}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - dev-db
      - prod-db
  prod-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dev-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ss
    ports:
      - "5433:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

